apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-native.yml
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: mongo-db
  name: mongo-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mongo-db
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-native.yml
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: mongo-db
    spec:
      containers:
        - image: asia-south2-docker.pkg.dev/quarkuslearning/quarkus-learning-repo/mongo:tag1
          name: mongo-db-server
          ports:
            - containerPort: 27017
          resources: {}
      restartPolicy: Always
status: {}
